version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"
  SRC: "src/mojo_std"

# global env:
env:
  ENV1: testing

################################################################################################

tasks:
  e:
    cmds:
      - modular host-info
      - modular config-list
      - modular --version
      - mojo --version
      - echo $MODULAR_HOME

  r:
    aliases: [run]
    cmds:
      - |
        mojo {{ .SRC }}/try_01_algo.mojo

  # run all:
  ra:
    aliases: [run:all]
    cmds:
      - task: r1
      - task: r2
      - task: r3
      - task: r4
      - task: r5
      - task: r6
      - task: r10
    ignore_errors: true

  r10:
    aliases: [run10]
    cmds:
      - mojo {{ .SRC }}/try_10_path.mojo

  r6:
    aliases: [run6]
    cmds:
      - mojo {{ .SRC }}/try_06_traits.mojo

  r5:
    aliases: [run5]
    cmds:
      - mojo {{ .SRC }}/try_05_structs.mojo

  r4:
    aliases: [run4]
    cmds:
      - mojo {{ .SRC }}/try_04_benchmark.mojo
      - mojo {{ .SRC }}/try_04b.mojo
      - mojo {{ .SRC }}/try_04c.mojo

  r3:
    aliases: [run3]
    cmds:
      - mojo {{ .SRC }}/try_03_base64.mojo

  r2:
    aliases: [run2]
    cmds:
      - mojo {{ .SRC }}/try_02.mojo
      - mojo {{ .SRC }}/try_02b.mojo
      - mojo {{ .SRC }}/try_02c.mojo
      - mojo {{ .SRC }}/try_02d.mojo
      - mojo {{ .SRC }}/try_02e.mojo
      - mojo {{ .SRC }}/try_02f.mojo
      - mojo {{ .SRC }}/try_02g.mojo
      - mojo {{ .SRC }}/try_02h_use_py.mojo -I .

  r1:
    aliases: [run1]
    cmds:
      - echo {{ .SRC }}
      - echo ${SRC}
      - mojo {{ .SRC }}/try_01_algo.mojo
      - mojo {{ .SRC }}/try_01b.mojo
      - mojo {{ .SRC }}/try_01c.mojo

  br1:
    aliases: [build:run1]
    cmds:
      - mkdir build/
      - mojo build {{ .SRC }}/try_01.mojo -o build/main
      - ./build/main
    ignore_error: true

  clean:
    aliases: [c]
    cmds:
      - rm -rf build
      - rm -rf dist
      - mkdir build
      - mkdir dist
    ignore_error: true

  help:
    aliases: [h]
    cmds:
      - mojo build --help

  ################################################################################################

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add click
      - poetry add jupyterlab notebook

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    aliases: [up]
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
